import { NextRequest, NextResponse } from 'next/server';
import {
  processCrisisInjection,
  calculateDivisionLoad,
  type DagTask,
  type DivisionLoad,
  type CrisisInjection,
} from '@/lib/dag-engine';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

/**
 * POST /api/dag/propagate
 *
 * Processes a crisis injection deterministically, then optionally
 * enriches mitigation options with AI summaries.
 *
 * Body: {
 *   tasks: DagTask[],
 *   divisions: DivisionLoad[],
 *   crisis: CrisisInjection,
 *   previousOCS: number,
 *   unresolvedIncidentSeverity: number,
 *   enrichWithAI?: boolean  // default true if API key exists
 * }
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      tasks,
      divisions,
      crisis,
      previousOCS = 100,
      unresolvedIncidentSeverity = 0,
      enrichWithAI = true,
    }: {
      tasks: DagTask[];
      divisions: DivisionLoad[];
      crisis: CrisisInjection;
      previousOCS: number;
      unresolvedIncidentSeverity: number;
      enrichWithAI?: boolean;
    } = body;

    if (!tasks || !crisis) {
      return NextResponse.json({ error: 'Missing required fields: tasks, crisis' }, { status: 400 });
    }

    // ── 1. Deterministic propagation (no AI) ────────────────────────────
    const result = processCrisisInjection(
      tasks,
      divisions,
      crisis,
      previousOCS,
      unresolvedIncidentSeverity
    );

    // ── 2. Enrich mitigation options with AI summaries (optional) ────────
    if (enrichWithAI && process.env.GEMINI_API_KEY && result.mitigationOptions.length > 0) {
      try {
        const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

        const prompt = `You are a 20-year veteran Stage Manager. A crisis has hit your event.
Your job is to provide raw, practical, and highly tactical field advice to mitigate it.

Crisis: "${crisis.incidentDescription}"
Delay: ${crisis.delayMinutes} minutes
Affected tasks: ${result.affectedTaskIds.length}

I will give you a list of deterministic mitigation options generated by the DAG engine.
For EACH option, provide:
1. "aiSummary": 1-2 sentences of tactical field advice (e.g. "Skip full soundcheck, line check only. Reallocate 2 crew to lighting.").
2. "whatsappDraft": A short, punchy bulleted message ready to be copy-pasted to the crew's WhatsApp group to execute this option.

Options:
${result.mitigationOptions.map((o, i) => `${i + 1}. ${o.title}: ${o.description}`).join('\n')}

Respond ONLY with a JSON array of objects, one per option, matching this exact schema:
[
  { "aiSummary": "...", "whatsappDraft": "..." },
  ...
]`;

        const aiResult = await model.generateContent(prompt);
        const text = aiResult.response.text().replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

        try {
          const summaries: { aiSummary: string; whatsappDraft: string }[] = JSON.parse(text);
          result.mitigationOptions = result.mitigationOptions.map((opt, i) => ({
            ...opt,
            aiSummary: summaries[i]?.aiSummary || opt.description,
            whatsappDraft: summaries[i]?.whatsappDraft || `CRISIS ALERT: ${crisis.incidentDescription}\nMitigation: ${opt.title}\nAction required immediately.`,
          }));
        } catch {
          // AI parse failed — use deterministic descriptions as fallback
        }
      } catch {
        // AI call failed — silently continue with deterministic results
      }
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error('[DAG Propagate] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error during crisis propagation' },
      { status: 500 }
    );
  }
}
