export interface ReportPdfSection {
  title: string;
  content: string;
}

export function buildReportHtml(
  eventName: string,
  sections: ReportPdfSection[],
  generatedAt = new Date().toISOString()
): string {
  const sectionHtml = sections
    .map(
      s => `
      <section style="margin-bottom: 28px; page-break-inside: avoid;">
        <h2 style="color: #0d9488; font-size: 18px; border-bottom: 2px solid #25D0AB; padding-bottom: 6px; margin-bottom: 12px;">${escapeHtml(s.title)}</h2>
        <div style="font-size: 13px; line-height: 1.65; color: #1f2937;">${markdownToSimpleHtml(s.content)}</div>
      </section>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(eventName)} — RunIT Report</title>
  <style>
    @page { margin: 20mm 15mm; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; padding: 24px; color: #111; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .meta { font-size: 11px; color: #6b7280; margin-bottom: 24px; }
    .footer { margin-top: 32px; font-size: 10px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(eventName)}</h1>
    <p class="meta">RunIT Post-Event Pack · Generated ${new Date(generatedAt).toLocaleString('id-ID')}</p>
  </header>
  ${sectionHtml}
  <div class="footer">Generated by RunIT Event Execution Platform</div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function markdownToSimpleHtml(md: string): string {
  if (!md) return '<p><em>No content</em></p>';
  return escapeHtml(md)
    .replace(/^### (.+)$/gm, '<h4 style="margin:14px 0 6px;font-size:14px;">$1</h4>')
    .replace(/^## (.+)$/gm, '<h3 style="margin:16px 0 8px;font-size:15px;">$1</h3>')
    .replace(/^# (.+)$/gm, '<h2 style="margin:18px 0 8px;font-size:16px;">$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^• (.+)$/gm, '<li style="margin-left:16px;">$1</li>')
    .replace(/^- (.+)$/gm, '<li style="margin-left:16px;">$1</li>')
    .replace(/\n\n/g, '<br/><br/>')
    .replace(/\n/g, '<br/>');
}

export function buildEventPackSections(modules: Record<string, unknown>): ReportPdfSection[] {
  const sections: ReportPdfSection[] = [];

  if (typeof modules.report === 'string') {
    sections.push({ title: 'LPJ Utama (Laporan Pertanggungjawaban)', content: modules.report });
  }
  if (typeof modules.sponsorReport === 'string') {
    sections.push({ title: 'Laporan Sponsor', content: modules.sponsorReport });
  }
  if (modules.lessons && typeof modules.lessons === 'object') {
    const l = modules.lessons as { summary?: string; strengths?: string[]; improvements?: string[]; actionItems?: string[] };
    let content = l.summary || '';
    if (l.strengths?.length) content += `\n\n**Kekuatan:**\n${l.strengths.map(s => `- ${s}`).join('\n')}`;
    if (l.improvements?.length) content += `\n\n**Perbaikan:**\n${l.improvements.map(s => `- ${s}`).join('\n')}`;
    if (l.actionItems?.length) content += `\n\n**Action Items:**\n${l.actionItems.map(s => `- ${s}`).join('\n')}`;
    sections.push({ title: 'Lessons Learned', content });
  }
  if (modules.reconciliation && typeof modules.reconciliation === 'object') {
    const r = modules.reconciliation as { summary?: string; categories?: Array<{ label: string; estimated: number; actual: number; variancePct: number }> };
    let content = r.summary || '';
    if (r.categories?.length) {
      content += '\n\n' + r.categories.map(c =>
        `${c.label}: Rp ${c.estimated.toLocaleString('id-ID')} → Rp ${c.actual.toLocaleString('id-ID')} (${c.variancePct > 0 ? '+' : ''}${c.variancePct}%)`
      ).join('\n');
    }
    sections.push({ title: 'Rekonsiliasi Keuangan', content });
  }

  return sections;
}
